Continuation of data exploration with the cleaned up data

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

df = pd.read_pickle(r'C:\Users\alexa\Downloads\aug24_bds_int---co2\notebooks\AllEU30.pkl')

display(df.head())

,ID,Country,Mh,Tan,T,Va,Ve,Cn,Ct,Cr,...,Ewltp (g/km),W (mm),At1 (mm),At2 (mm),Ft,Fm,ec (cm3),ep (KW),Status,year
2665338,3700529.0,FR,AUTOMOBILES PEUGEOT,e2*2007/46*0070*40,C,AHMR,P/S,208,M1,M1,...,130.0,2538.0,1470.0,1470.0,Petrol,M,1199.0,61.0,P,2017.0
2665354,3707627.0,FR,AUTOMOBILES PEUGEOT,e2*2007/46*0070*40,C,AHMR,P/S,208,M1,M1,...,131.0,2538.0,1470.0,1470.0,Petrol,M,1199.0,61.0,P,2017.0
2665373,3696204.0,FR,AUTOMOBILES PEUGEOT,e2*2007/46*0070*40,C,AHMR,P/S,208,M1,M1,...,129.0,2538.0,1470.0,1470.0,Petrol,M,1199.0,61.0,P,2017.0
2665374,3696214.0,FR,AUTOMOBILES PEUGEOT,e2*2007/46*0070*40,C,AHMR,P/S,208,M1,M1,...,131.0,2538.0,1470.0,1470.0,Petrol,M,1199.0,61.0,P,2017.0
2665382,3709072.0,FR,AUTOMOBILES PEUGEOT,e2*2007/46*0070*40,C,AHMR,P/S,208,M1,M1,...,132.0,2538.0,1470.0,1470.0,Petrol,M,1199.0,61.0,P,2017.0

Next steps:

1- Standardization of num variables
2- Encoding cat variables

3- Visualization num variables
4- Visualization cat variables

In [ ]:
# Standardization of num variables

numerical_cols = AllEU30.select_dtypes(include=['float32', 'int64']).columns

scaler = StandardScaler()
AllEU30[numerical_cols] = scaler.fit_transform(AllEU30[numerical_cols])

In [ ]:
# Encoding categorical variables / get_dummies do not work. Out of memory.
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
#df['Categorical_Column'] = le.fit_transform(df['Categorical_Column'])